builders:
  prep:
    import: 'package:artemis/prep_builder.dart'
    builder_factories: ['prepBuilder']
    build_extensions: {'$lib$': ['.executable.dart']}
    auto_apply: dependents
    build_to: cache
    runs_before: ['artemis|runner']
    applies_builders: ['artemis|runner']
  artemis:
    import: 'package:artemis/builder.dart'
    builder_factories: ['graphQLQueryBuilder']
    build_extensions: {'$lib$': ['.graphql.dart']}
    auto_apply: dependents
    build_to: source
    applies_builders: ['json_serializable']
    runs_before: ['json_serializable']
