targets:
  $default:
    sources:
      - lib/**
      - graphql/**
      - pokemon.schema.json
    builders:
      artemis:
        options:
          schema_mapping:
            - schema: pokemon.schema.json
              mapping:
                graphql/simple_query.graphql: lib/graphql/simple_query.dart
                graphql/big_query.graphql: lib/graphql/big_query.dart
