name: graphbrainz_example
version: 0.0.1

authors:
  - Igor Borges <igor@borges.me>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  http: ^0.12.0+2

dev_dependencies:
  test: ^1.0.0
  build_runner: ^1.2.8
  json_serializable: ^2.0.0
  artemis:
    path: ../../.
